DROP TABLE IF EXISTS email_logs;
DROP TABLE IF EXISTS sms_logs;
DROP TABLE IF EXISTS whatsapp_logs;

CREATE TABLE email_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email_to VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sms_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mobile_number VARCHAR(30) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE whatsapp_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mobile_number VARCHAR(30) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);